[[YAJL]]
arch = "i686"
git-tree-sha1 = "24e3ba0b6961db4a048dbee199851bca1d497e69"
libc = "musl"
os = "linux"

    [[YAJL.download]]
    sha256 = "dc2714e22dcc12f7eaf636f9cec72d829b96dfa137991568c9a0051ba54c6901"
    url = "https://github.com/JuliaBinaryWrappers/YAJL_jll.jl/releases/download/YAJL-v2.1.0+0/YAJL.v2.1.0.i686-linux-musl.tar.gz"
[[YAJL]]
arch = "aarch64"
git-tree-sha1 = "334a929e5c143683ce607d18f73b16d7e7b04b74"
libc = "musl"
os = "linux"

    [[YAJL.download]]
    sha256 = "0091106a602ed13b0cf58babd4331a20cfa0898c037366ea9a358f8b338f6a00"
    url = "https://github.com/JuliaBinaryWrappers/YAJL_jll.jl/releases/download/YAJL-v2.1.0+0/YAJL.v2.1.0.aarch64-linux-musl.tar.gz"
[[YAJL]]
arch = "i686"
git-tree-sha1 = "fa10aed797427a37a23f3c0f62736014ec0f6be4"
os = "windows"

    [[YAJL.download]]
    sha256 = "2d4f8028cce14a129831d3b0729131d78328f72bbfc2161e0d9f4e3217e4e065"
    url = "https://github.com/JuliaBinaryWrappers/YAJL_jll.jl/releases/download/YAJL-v2.1.0+0/YAJL.v2.1.0.i686-w64-mingw32.tar.gz"
[[YAJL]]
arch = "x86_64"
git-tree-sha1 = "ffa6d5c8f6d1422af3beca14ca03e226de642e5d"
os = "windows"

    [[YAJL.download]]
    sha256 = "b8f46f3f43a2010d6c7c8293af8173a1a6cd9be47a9790039e9ccf86ed55b93c"
    url = "https://github.com/JuliaBinaryWrappers/YAJL_jll.jl/releases/download/YAJL-v2.1.0+0/YAJL.v2.1.0.x86_64-w64-mingw32.tar.gz"
[[YAJL]]
arch = "armv7l"
git-tree-sha1 = "6363adcbebd0bd318d344bb3e08f5382e00d740f"
libc = "glibc"
os = "linux"

    [[YAJL.download]]
    sha256 = "89f7ce8c6926691a7c76009e3af6a24425ce46eb1bf2fbb04a3a1a2c2ebb34c3"
    url = "https://github.com/JuliaBinaryWrappers/YAJL_jll.jl/releases/download/YAJL-v2.1.0+0/YAJL.v2.1.0.armv7l-linux-gnueabihf.tar.gz"
[[YAJL]]
arch = "armv7l"
git-tree-sha1 = "c49fbbf19df3a380f9fc0e8d49a0b62575cd3e74"
libc = "musl"
os = "linux"

    [[YAJL.download]]
    sha256 = "32dccfbd8a4f60e78c23d29bc5c0ca8729d3b74388f0742b3458f06e8b1c7dbd"
    url = "https://github.com/JuliaBinaryWrappers/YAJL_jll.jl/releases/download/YAJL-v2.1.0+0/YAJL.v2.1.0.armv7l-linux-musleabihf.tar.gz"
[[YAJL]]
arch = "i686"
git-tree-sha1 = "6879205d5408884857fc4f72ad1d83a1fd4e16d0"
libc = "glibc"
os = "linux"

    [[YAJL.download]]
    sha256 = "f34ede4eaac9bc541cdf11a130a26488fd24caf0ff808b04ca197649bfd6fab0"
    url = "https://github.com/JuliaBinaryWrappers/YAJL_jll.jl/releases/download/YAJL-v2.1.0+0/YAJL.v2.1.0.i686-linux-gnu.tar.gz"
[[YAJL]]
arch = "x86_64"
git-tree-sha1 = "590605ba50600f2ee3ccffe0d22576154c0ff0d4"
libc = "glibc"
os = "linux"

    [[YAJL.download]]
    sha256 = "91da605f858504319d1c8bcfda22164d1d79ac0a99a7a790cae7b69403721f95"
    url = "https://github.com/JuliaBinaryWrappers/YAJL_jll.jl/releases/download/YAJL-v2.1.0+0/YAJL.v2.1.0.x86_64-linux-gnu.tar.gz"
[[YAJL]]
arch = "powerpc64le"
git-tree-sha1 = "138f1da614e69c6e839611df08756a3ee8e9344d"
libc = "glibc"
os = "linux"

    [[YAJL.download]]
    sha256 = "747bd90cd0a54407dd530423785e66e3c612f05da66196a90fc7208f4d500b98"
    url = "https://github.com/JuliaBinaryWrappers/YAJL_jll.jl/releases/download/YAJL-v2.1.0+0/YAJL.v2.1.0.powerpc64le-linux-gnu.tar.gz"
[[YAJL]]
arch = "x86_64"
git-tree-sha1 = "f54099e9cb96bc76ede2790cf123d3474d5d0849"
os = "macos"

    [[YAJL.download]]
    sha256 = "b0a6f4b9db937de5b911fb62adf37bda2db668497e4e8a9519736d96edcff46a"
    url = "https://github.com/JuliaBinaryWrappers/YAJL_jll.jl/releases/download/YAJL-v2.1.0+0/YAJL.v2.1.0.x86_64-apple-darwin14.tar.gz"
[[YAJL]]
arch = "aarch64"
git-tree-sha1 = "e24a5103a4809892a44a65e09c21e5838d34d698"
libc = "glibc"
os = "linux"

    [[YAJL.download]]
    sha256 = "55fecba26d2809b388449d76b7e8bd3f27017892c4c9ded4081e9ad442c18a68"
    url = "https://github.com/JuliaBinaryWrappers/YAJL_jll.jl/releases/download/YAJL-v2.1.0+0/YAJL.v2.1.0.aarch64-linux-gnu.tar.gz"
[[YAJL]]
arch = "x86_64"
git-tree-sha1 = "78ce61b3aa2b804ea07279b82e636fb9f9cebeee"
os = "freebsd"

    [[YAJL.download]]
    sha256 = "7e0ba43ceb030783341e24882c5a326f9d90a3d0b60403cbf6c6bc4499ec70ea"
    url = "https://github.com/JuliaBinaryWrappers/YAJL_jll.jl/releases/download/YAJL-v2.1.0+0/YAJL.v2.1.0.x86_64-unknown-freebsd11.1.tar.gz"
[[YAJL]]
arch = "x86_64"
git-tree-sha1 = "9a21ae06e70622c958a341fb3627609c8ea0f76a"
libc = "musl"
os = "linux"

    [[YAJL.download]]
    sha256 = "d9bb328392181b75d8ef98c8b591e12d47d25a30ae40ed9de37778d04f2c5bd9"
    url = "https://github.com/JuliaBinaryWrappers/YAJL_jll.jl/releases/download/YAJL-v2.1.0+0/YAJL.v2.1.0.x86_64-linux-musl.tar.gz"
