[[YAJL]]
arch = "aarch64"
git-tree-sha1 = "71ec786b58ff17adcdca12c1e37d98028d7325f3"
os = "macos"

    [[YAJL.download]]
    sha256 = "06d22ea523a161b895f9c2e0878aef24a90a93a7568460b9a31859dcee7fdfee"
    url = "https://github.com/JuliaBinaryWrappers/YAJL_jll.jl/releases/download/YAJL-v2.1.1+0/YAJL.v2.1.1.aarch64-apple-darwin.tar.gz"
[[YAJL]]
arch = "aarch64"
git-tree-sha1 = "2d425ccdebe35c59cd49ff7ae94f2d39f340b428"
libc = "glibc"
os = "linux"

    [[YAJL.download]]
    sha256 = "1e4f364e47eb3a97577e5a657c3c8045cf4b2d184dc5d47a694e306494989ce4"
    url = "https://github.com/JuliaBinaryWrappers/YAJL_jll.jl/releases/download/YAJL-v2.1.1+0/YAJL.v2.1.1.aarch64-linux-gnu.tar.gz"
[[YAJL]]
arch = "aarch64"
git-tree-sha1 = "e32fb82ca157334b755fc11a2da989de5efedab2"
libc = "musl"
os = "linux"

    [[YAJL.download]]
    sha256 = "0a0c60a78bd0d4d0b8d4357c0ef93cdd90ee73d4ecb49c4c837cf40b964f23ea"
    url = "https://github.com/JuliaBinaryWrappers/YAJL_jll.jl/releases/download/YAJL-v2.1.1+0/YAJL.v2.1.1.aarch64-linux-musl.tar.gz"
[[YAJL]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "d74f397c258bb839683af05d518930fb9fd7966f"
libc = "glibc"
os = "linux"

    [[YAJL.download]]
    sha256 = "325512844d0db002880d97911cf64f2813b0d52a2403853939759f82cd5bfbfc"
    url = "https://github.com/JuliaBinaryWrappers/YAJL_jll.jl/releases/download/YAJL-v2.1.1+0/YAJL.v2.1.1.armv6l-linux-gnueabihf.tar.gz"
[[YAJL]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "9f7e6d17896e82a9358ff0fbbfb5b2b72dd269fa"
libc = "musl"
os = "linux"

    [[YAJL.download]]
    sha256 = "072d1fa706aec398504e503d4c1bb80f72f7f805a0607ea5e2ffaf6eb94a1f7d"
    url = "https://github.com/JuliaBinaryWrappers/YAJL_jll.jl/releases/download/YAJL-v2.1.1+0/YAJL.v2.1.1.armv6l-linux-musleabihf.tar.gz"
[[YAJL]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "f8f587fe46f79e3383c04a982f79353c727906d4"
libc = "glibc"
os = "linux"

    [[YAJL.download]]
    sha256 = "97a7433da68532c2f8096fd39ccf947c63f8d9d3c957f7ade1d768cdd6dfa3d1"
    url = "https://github.com/JuliaBinaryWrappers/YAJL_jll.jl/releases/download/YAJL-v2.1.1+0/YAJL.v2.1.1.armv7l-linux-gnueabihf.tar.gz"
[[YAJL]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "297faef87302b529faabfc8430846b1eca1f6cba"
libc = "musl"
os = "linux"

    [[YAJL.download]]
    sha256 = "58a963873787d93c80ef1120ee8eb0c946d3a800007af544c3c8eda639ca0080"
    url = "https://github.com/JuliaBinaryWrappers/YAJL_jll.jl/releases/download/YAJL-v2.1.1+0/YAJL.v2.1.1.armv7l-linux-musleabihf.tar.gz"
[[YAJL]]
arch = "i686"
git-tree-sha1 = "9ffe53d09388c7ba5882cc706f8ff18dcf1214b2"
libc = "glibc"
os = "linux"

    [[YAJL.download]]
    sha256 = "85e5ce518fbd98c0527895ada183d05f000b3e3f3c953818f582d715a6d8be1d"
    url = "https://github.com/JuliaBinaryWrappers/YAJL_jll.jl/releases/download/YAJL-v2.1.1+0/YAJL.v2.1.1.i686-linux-gnu.tar.gz"
[[YAJL]]
arch = "i686"
git-tree-sha1 = "f839f7caa84f7f6de3380888a6a6fd6fb09e1c89"
libc = "musl"
os = "linux"

    [[YAJL.download]]
    sha256 = "56b67065c7be11494cdcc09c1aa7895e2ce8d5e2e2585d79f6dad967fa4a5481"
    url = "https://github.com/JuliaBinaryWrappers/YAJL_jll.jl/releases/download/YAJL-v2.1.1+0/YAJL.v2.1.1.i686-linux-musl.tar.gz"
[[YAJL]]
arch = "i686"
git-tree-sha1 = "621840c51ca10e141409f87232ebf2e86da23aef"
os = "windows"

    [[YAJL.download]]
    sha256 = "0d186e32c3006bcfd87dcf8b2f3cb17598ffc2ed665234d5b63789e9afb73bb9"
    url = "https://github.com/JuliaBinaryWrappers/YAJL_jll.jl/releases/download/YAJL-v2.1.1+0/YAJL.v2.1.1.i686-w64-mingw32.tar.gz"
[[YAJL]]
arch = "powerpc64le"
git-tree-sha1 = "5efd865c052b83c15cee18177af5e817d9889f74"
libc = "glibc"
os = "linux"

    [[YAJL.download]]
    sha256 = "ac7b0b1e9a46f7e2da6b0130b804e14ba8619db86e418a602fa6898e5194c3c7"
    url = "https://github.com/JuliaBinaryWrappers/YAJL_jll.jl/releases/download/YAJL-v2.1.1+0/YAJL.v2.1.1.powerpc64le-linux-gnu.tar.gz"
[[YAJL]]
arch = "x86_64"
git-tree-sha1 = "b8f3a425230bae46f3316bed0405ff33e53c4ae1"
os = "macos"

    [[YAJL.download]]
    sha256 = "692c3701cf6f7a91e1820b77a52872e843be5f0ed062420a7a833cc34ab69e3b"
    url = "https://github.com/JuliaBinaryWrappers/YAJL_jll.jl/releases/download/YAJL-v2.1.1+0/YAJL.v2.1.1.x86_64-apple-darwin.tar.gz"
[[YAJL]]
arch = "x86_64"
git-tree-sha1 = "70139997726c9e01c5d8678ef077150a06f29dea"
libc = "glibc"
os = "linux"

    [[YAJL.download]]
    sha256 = "94fcb4b05788257fc6efa0be820e0c10acff8054117613ecf65a2a8f358d7921"
    url = "https://github.com/JuliaBinaryWrappers/YAJL_jll.jl/releases/download/YAJL-v2.1.1+0/YAJL.v2.1.1.x86_64-linux-gnu.tar.gz"
[[YAJL]]
arch = "x86_64"
git-tree-sha1 = "a66218ab098c29bfbfa14706e6e632d434ad7033"
libc = "musl"
os = "linux"

    [[YAJL.download]]
    sha256 = "f750c8b8e487535d0e4141b4b3ff2f10c7994212afe4f7c27fe05c6dbc7cf52f"
    url = "https://github.com/JuliaBinaryWrappers/YAJL_jll.jl/releases/download/YAJL-v2.1.1+0/YAJL.v2.1.1.x86_64-linux-musl.tar.gz"
[[YAJL]]
arch = "x86_64"
git-tree-sha1 = "cf87d4c2f466f400ef1750b096fecb0f8fdc20c6"
os = "freebsd"

    [[YAJL.download]]
    sha256 = "521128082f2a468eff71eca821157dea98baf49a80a605053b26cb8be618605a"
    url = "https://github.com/JuliaBinaryWrappers/YAJL_jll.jl/releases/download/YAJL-v2.1.1+0/YAJL.v2.1.1.x86_64-unknown-freebsd.tar.gz"
[[YAJL]]
arch = "x86_64"
git-tree-sha1 = "d7f073193d1ceeb5f927cdad549e2bec781cc0c3"
os = "windows"

    [[YAJL.download]]
    sha256 = "9165df33c34bff4cc485127e39f3afe226a3316af67f4011a8d671fc39e73d69"
    url = "https://github.com/JuliaBinaryWrappers/YAJL_jll.jl/releases/download/YAJL-v2.1.1+0/YAJL.v2.1.1.x86_64-w64-mingw32.tar.gz"
