# Autogenerated wrapper script for YAJL_jll for aarch64-apple-darwin
export libyajl

JLLWrappers.@generate_wrapper_header("YAJL")
JLLWrappers.@declare_library_product(libyajl, "@rpath/libyajl.2.dylib")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libyajl,
        "lib/libyajl.2.1.0.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
