# Autogenerated wrapper script for YAJL_jll for i686-w64-mingw32
export libyajl

JLLWrappers.@generate_wrapper_header("YAJL")
JLLWrappers.@declare_library_product(libyajl, "libyajl.dll")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libyajl,
        "bin\\libyajl.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
